version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '54321:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - '63798:6379'
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local